# https://packit.dev/docs/configuration/

specfile_path: osbuild-composer.spec

synced_files:
    - osbuild-composer.spec
    - .packit.yaml

upstream_package_name: osbuild-composer
downstream_package_name: osbuild-composer

upstream_tag_template: v{version}

actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"

jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
      - fedora-rawhide
